apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: user
spec:
  request: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2R6Q0NBVjhDQVFBd01qRU9N
    QXdHQTFVRUF3d0ZkWE5sY2pJeER6QU5CZ05WQkFvTUJtZHliM1Z3TVRFUApNQTBHQTFVRUNnd0da
    M0p2ZFhBeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCnJyemtR
    SENVbU9lR2RVUlZpeUw5QWRCSTZGNm9KblludUZ3Q040dTFNYUQ1Rk16TWN4R1JRQXZsYWoweUJ2
    OWsKcFZUNzJWcmhpV2JhSzdxL0dsQUNGRmFjSXB2ZGJXL3lDbG9TcFN2cmhQZXdQT1NQTnkrenRD
    eHhLTm5NdEJtMwpsMXEwRDJIaGRBa2FhMkQ4dTd6eEllQ1BnTStINURoNlUwa1RVcU1MVE8zUjlH
    MDM3NVNUUWxRRnFvVGgvTUlqCkh4Z05YZGVDc1Y0YUJxZkY2SDlXMUtneFZrNVcraDhhbjdwckdE
    Q3YzeDBIN2ZXdGJpQm9UOG0vcnpYZVV5OWoKKzVZYnlYV0RweWZsRUZDaGRtVmE2UWlaRXdmSm1a
    VFJKZEYwZkFrYk5KNnNSMmNxdldmU1o5QmpGeVhML0FubQorVlFaSHZPelJIUXQ1V0pKaEVYaCt3
    SURBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFSFRMbTR4CmhSUy9QWjdwOVl0b3Ay
    bXc1QXd4TGJSSDI2a3ZWNWoxNi9IMVZibVUwdVNCT2RHa2lyUEZDODRzUTF0cnppbUUKTnU0cWFP
    WFo3K0s2UENOTUVkRkhqRERsRHdhNWxXUWxIeEV6N2I5UXd4WnMyU0FsdUo2cENqSWhTVUpEa1hl
    OApZQWpXeFMwUzJQbXpqMkp6Z3YvUFE2eVR6anlSbE9sbElGd1ZBa2lLTitTT2xPd1I5cWV5M1dn
    SmE1SUVDSERqCmhJQzdodHJDUWM2MytkZGJqQUxqeWx0aUt3S1ZwREFsanIrVnlDL1M1dXdxL3Vx
    Rzd4dFphMzRjZlZUUlF3bXgKWE4yalV5MHNzU3hXTUNZYVFFUW5kWlR3L3k0cUJ4UmxSQjd2bEFG
    d0x2aG04VURKQlFtQmtEdGFxdDlVQXV4SgpETGhPdlhwWHhNa3cwRDA9Ci0tLS0tRU5EIENFUlRJ
    RklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages: ['digital signature', 'key encipherment',
    'client auth']
# kubectl certificate approve user 
status:
  certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXakNDQWtLZ0F3SUJBZ0lUTUQ0N1JsM2phdmsraGpGamRHRk1SUDQxSURBTkJna3Foa2lHOXcwQkFRc0YKQURBb01SSXdFQVlEVlFRRERBbEZZWE41VTNSaFkyc3hFakFRQmdOVkJBb01DVVZoYzNsVGRHRmphekFlRncweQpNVEV5TWpNd056QXdNREJhRncweU1qRXlNak13TnpBd01EQmFNREF4SGpBTkJnTlZCQW9UQm1keWIzVndNVEFOCkJnTlZCQW9UQm1keWIzVndNakVPTUF3R0ExVUVBeE1GZFhObGNqSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUEKQTRJQkR3QXdnZ0VLQW9JQkFRQ3V2T1JBY0pTWTU0WjFSRldMSXYwQjBFam9YcWdtZGllNFhBSTNpN1V4b1BrVQp6TXh6RVpGQUMrVnFQVElHLzJTbFZQdlpXdUdKWnRvcnVyOGFVQUlVVnB3aW05MXRiL0lLV2hLbEsrdUU5N0E4CjVJODNMN08wTEhFbzJjeTBHYmVYV3JRUFllRjBDUnByWVB5N3ZQRWg0SStBejRma09IcFRTUk5Tb3d0TTdkSDAKYlRmdmxKTkNWQVdxaE9IOHdpTWZHQTFkMTRLeFhob0dwOFhvZjFiVXFERldUbGI2SHhxZnVtc1lNSy9mSFFmdAo5YTF1SUdoUHliK3ZOZDVUTDJQN2xodkpkWU9uSitVUVVLRjJaVnJwQ0prVEI4bVpsTkVsMFhSOENSczBucXhIClp5cTlaOUpuMEdNWEpjdjhDZWI1VkJrZTg3TkVkQzNsWWttRVJlSDdBZ01CQUFHamRUQnpNQTRHQTFVZER3RUIKL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZApEZ1FXQkJRV1J0UXdTbWlCUlVwMTJqZVhBK2h4NXA1SlpUQWZCZ05WSFNNRUdEQVdnQlR3UXdiNWNjTW5TSUhvCnJFT3poVFFrY2pOZFZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFTWExSZ1FCNGF3S0txWG1YVERKK2VIWHEKbWo1R1RZRGF6bnA3d3BtWHFSYTJicUFiUDhLV2FlQTdIa2E4U0FOa2tMNGVRcUppY0djZldTYXVZMmNlQ0RZaQpWSTAzT2tWVlR3dDljS3M0MTgwL2tRMXVwQkRhR3RSejlQNm5kUHA2TW1yWDVxdG9KMmdCRmpZUzc2Ky9mdGZhCnlwNEZVSDZHQUJ3NGttTlEwd3ZhcnFhQWJxL25GTmhvUnp6RjdIU0FuZEJDOUlEQjVVTnhxVlhlNTlIaWxGSWwKakhwbDV5Q0tVNm1rckZ4QzJLLzYxNWZBK3hBWXlRM0ljcmorUDFaRnplbVAwbS9oOWFMUnRXdTgxYVcwRkxyMQpGNW5hUEplZE9OaTZJWlliTHRwZUJBSnhRd2ZsNjZKang3OFUvV1Q4VTFWYkRRNE5ER0VlMXRNZWZFZEk1QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  conditions:
  - lastUpdateTime: "2020-12-23T07:04:47Z"
    message: This CSR was approved by kubectl certificate approve.
    reason: KubectlApprove
    type: Approved