name: arm kubernetes

on:
  push:
    branches: [ buildx ]
  pull_request:
    branches: [ buildx ]

env:
  GO111MODULE: on 
  PROJECT: kubernetes
  BRANCH: v1.16.6-es

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out repo code
      uses: actions/checkout@v2

    - name: Check out build code
      uses: actions/checkout@v2
      with:
        repository: easystack/kubernetes
        ref: ${{ env.BRANCH }}
        token: ${{ secrets.KPULL }}  
        path: ${{ env.PROJECT }}

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3
    
    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: yylt
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Docker Buildx (push)
      run: |
        docker buildx build \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --platform linux/arm64 \
          --output "type=image,push=true" \
          --tag yylt/hyperkube-arm64:${{ env.BRANCH }} \
          --file ./Dockerfile-arm64 ./