name: kubernetes

on:
  push:
    branches: [ k8s ]
  pull_request:
    branches: [ k8s ]

env:
  GO111MODULE: on 
  PROJECT: kubernetes
  BRANCH: overquota
  GIT_VERSION: v1.16.6-es3

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.14
      id: go

    - name: Check out repo code
      uses: actions/checkout@v2

    - name: Check out build code
      uses: actions/checkout@v2
      with:
        repository: yylt/kubernetes-1
        ref: ${{ env.BRANCH }}
        token: ${{ secrets.KPULL }}  
        path: ${{ env.PROJECT }}

    - name: Build amd64
      run: |
        export KUBE_GIT_COMMIT=""
        export KUBE_GIT_VERSION=${{ env.GIT_VERSION }}
        export KUBE_BUILD_PLATFORMS=linux/amd64
        cd ${{ env.PROJECT }} 
        make WHAT=cmd/hyperkube


    - name: Build arm64
      run: |
        sudo apt-get update && sudo apt-get install -y crossbuild-essential-arm64
        export KUBE_GIT_COMMIT=""
        export KUBE_GIT_VERSION=${{ env.GIT_VERSION }}
        export KUBE_BUILD_PLATFORMS=linux/arm64
        cd ${{ env.PROJECT }} 
        make WHAT=cmd/hyperkube
    
