name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GO111MODULE: on 
  PROJECT: kubernetes
  BRANCH: v1.16.6-es

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go
    - name: name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - name: Check out repo code
      uses: actions/checkout@v2

    - name: Check out build code
      uses: actions/checkout@v2
      with:
        repository: https://github.com/easystack/kubernetes
        ref: ${{ env.BRANCH }}
        token: ${{ secret.KPULL }}  
        path: ${{ env.PROJECT }}

    - name: Build amd64
      run: make PROJECT=${{ env.PROJECT }} ARCH=amd64
    
    - name: build and push amd64 image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: yylt
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: yylt/hyperkube-amd64
        image_tag: ${{ env.BRANCH }}
        dockerfile: Dockerfile-kubernetes-amd64

    - name: Build arm64
      run:  make PROJECT=${{ env.PROJECT }} ARCH=arm64
    
    - name: build and push arm64 image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: yylt
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
        image_name: yylt/hyperkube-arm64
        image_tag: ${{ env.BRANCH }}
        dockerfile: Dockerfile-kubernetes-arm64
